name: CI

on:
  push:
    branches:
    - '**'
  pull_request_target:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: mirror-repository
      run: |
          mkdir ~/.ssh
          echo "${GIT_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa -o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
          git remote add mirror "${REMOTE}"
          git remote show mirror
          git config --add remote.origin.fetch +refs/pull/*/head:refs/remotes/origin/pr
          git fetch origin
          git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'
          git push --tags --force --prune mirror 'refs/remotes/origin/pr/*:refs/pull/*/head'
      env:
        REMOTE: git@gitlab.com:cscs-ci/ci-testing/mirror.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
