name: CI

on:
  push:
    branches:
    - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: mirror-repository
      run: |
          mkdir ~/.ssh && \
          echo "${GIT_SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa && \
          chmod 600 ~/.ssh/id_rsa && \
          #ssh -v -i ~/.ssh/id_rsa -T git@gitlab.com
          ls ~/.ssh/id_rsa
          #export GIT_SSH_COMMAND='ssh -i ./id_rsa -o IdentitiesOnly=yes'
          #git remote add mirror "${REMOTE}"
          #git remote show mirror
          #git push --tags --force --prune mirror 'refs/remotes/origin/*:refs/heads/*'
      env:
        REMOTE: git@gitlab.com:cscs-ci/ci-testing/mirror.git
        GIT_SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_KEY }}
